language: python
python:
  - "2.7"
  - "3.6"

branches:
  only:
  - master
  - dev

env:
  global:
      - ES_VERSION=6.5.4
      - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz

install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"

# command to run tests
script:
  - "export PYTHONPATH=.:vendor"
  - "coverage run -m unittest discover tests"

after_success:
  - coveralls


